# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mpinson <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/03 17:42:11 by mpinson           #+#    #+#              #
#    Updated: 2016/11/04 12:27:08 by mpinson          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_display_file.c

all : $(NAME)

$(NAME) :
	gcc -o $(NAME) $(SRC)

clean :
	/bin/rm -f ft_display_file.o

fclean : clean
	/bin/rm -f $(NAME)

re : fclean all 
